#!/bin/zsh

pushd ${0:a:h}

conan install . --output-folder=build --build=missing &&
  cmake . -G "Ninja" --preset conan-release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON &&
  pushd build/build/Release &&
  ninja &&
  ctest &&
  popd

popd